DEBUG_MSG = True
TRUST_MOD = 0.2

GEN_OUTPUT_LENGTH_MAX = 32
GEN_OUTPUT_LENGTH_MIN = 8

CLS_MAX_LENGTH = 512
CLS_EPOCH_SIZE = 1600
CLS_BATCH_SIZE = 16
CLS_LEARNING_RATE = 3e-5

MAX_DATA_FOLDERS = 2

INPUT_DATA_PATH = ["data", "input"]
INPUT_PROTECTED_SUB = "base"
NLI_DATA_PATH = ["data", "nli_fever"]

MODEL_ROOT = ["models"]
GEN_NAME = "pythia-mod"
CLS_NAME = "inter-classifier"

# NOT IN USE
# GEN_BATCH_SIZE = 1
# GEN_LEARNING_RATE = 2e-5
# GEN_LR_STEP_SIZE = 10
# GEN_LR_GAMMA = 0.01
